<a href="https://colab.research.google.com/github/prashant3094/Intermediate-Python-Programming-Course/blob/main/Intermediate_Python_Programming_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_tuple="max","28","boston"
print(type(my_tuple))

<class 'tuple'>


In [ ]:
name,age,city=my_tuple
print(name)
print(age)
print(city)

max
28
boston


In [ ]:
my_tuple=(0,1,2,3,4)
i1,*i2,i3=my_tuple
print(i1)
print(i3)
print(i2)

0
4
[1, 2, 3]


In [ ]:
#tuples are more fater than list
import timeit
print(timeit.timeit(stmt="[0,1,2,3,4,5]",number=1000000))  #list
print(timeit.timeit(stmt="(0,1,2,3,4,5)",number=1000000))   #tuple 

0.09607780500000018
0.01246413399999824


#sets

sets are unordered , mutable and no duplicate

In [ ]:
my_set=([1,2,3])
print(my_set)

[1, 2, 3]


In [ ]:
my_set=set("hello")
print(my_set)

{'h', 'l', 'o', 'e'}


In [ ]:
my_set=set()
my_set.add(1)
my_set.add(2)
my_set.add(3)
print(my_set)

{1, 2, 3}


In [ ]:
odds={1,3,5,7,9}
evens={0,2,4,6,8}
prime={2,3,5,7}

In [ ]:
#union operation
u=odds.union(evens)
u

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
#intersection
i=odds.intersection(evens)
i

set()

In [ ]:
i=odds.intersection(prime)
i

{3, 5, 7}

In [ ]:
#concatinating strings
greetings="hello"
name="tom"
sentence= greetings+ " " +name
print(sentence)

hello tom


In [ ]:
#removing white spaces from string
my_string="    hello world  "
print(my_string)
my_string=my_string.strip()
my_string  #white space are removed

    hello world  


'hello world'

In [ ]:
my_string="hello world"
print(my_string.replace("world","universe"))

hello universe


In [ ]:
var=3.1234567
my_string="the variable is {}".format(var)
print(my_string)

the variable is 3.1234567


In [ ]:
var1=3.1234567
var2=6
my_string=f"the variable is {var1} and {var2}"
print(my_string)

the variable is 3.1234567 and 6


#collections

In [ ]:
from collections import Counter

In [ ]:
a="aaaaaaabbbbbccc"
my_counter=Counter(a)
print(my_counter)

Counter({'a': 7, 'b': 5, 'c': 3})


In [ ]:
print(my_counter.most_common(1))  #a is most common element in our string

[('a', 7)]


In [ ]:
print(list(my_counter.elements()))

['a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'c', 'c', 'c']


In [ ]:
from collections import namedtuple
point=namedtuple("point","x,y")
pt=point(1,-4)
print(pt.x,pt.y)

1 -4


In [ ]:
from collections import deque
d=deque()
d.append(1)
d.append(2)
print(d)

deque([1, 2])


#itertools

In [ ]:
from itertools import permutations
a=[1,2,3]
perm=permutations(a)
print(list(perm))  # we see all the different ordering

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [ ]:
from itertools import combinations
a=[1,2,3]
perm=combinations(a,2)
print(list(perm))  # 

[(1, 2), (1, 3), (2, 3)]


In [ ]:
from itertools import accumulate
a=[1,2,3,4]
acc=accumulate(a)
print(a)
print(list(acc))

[1, 2, 3, 4]
[1, 3, 6, 10]


#LAMBDA== One line function

In [ ]:
def add10_func(x):
  return x+10

add10_func(5)

15

In [ ]:
add10=lambda x : x+10
print(add10(5))

15


In [ ]:
mul=lambda x ,y :x* y
print(mul(2,7))

14


In [ ]:
#map function (function, sequence)
a=[1,2,3,4,5]
b=map(lambda x: x*2 ,a)
print(list(b))

[2, 4, 6, 8, 10]


In [ ]:
from functools import reduce
a=[1,2,3,4]
product_a=reduce(lambda x,y: x*y ,a )
print(product_a)

24


#logging

The logging module in Python is a powerful built-in module so you can quickly add logging to your application.

In [ ]:
import logging

In [ ]:
import logging
logging.debug('This is a debug message')
logging.info('This is an info message')
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')

ERROR:root:This is an error message
CRITICAL:root:This is a critical message


In [ ]:
import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', datefmt='%m/%d/%Y %H:%M:%S')
# Now also debug messages will get logged with a different format.
#logging.debug('Debug message')
logging.debug('This is a debug message')
logging.info('This is an info message')
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')

# This would log to a file instead of the console.
# logging.basicConfig(level=logging.DEBUG, filename='app.log')

ERROR:root:This is an error message
CRITICAL:root:This is a critical message


#json

JSON (JavaScript Object Notation) is a leightweight data format for data exchange. In Python you have the built-in json module for encoding and decoding JSON data. Simply import it and you are ready to work with JSON data:

In [ ]:
{
    "firstName": "Jane",
    "lastName": "Doe",
    "hobbies": ["running", "swimming", "singing"],
    "age": 28,
    "children": [
        {
            "firstName": "Alex",
            "age": 5
        },
        {
            "firstName": "Bob",
            "age": 7
        }
    ]
}

{'age': 28,
 'children': [{'age': 5, 'firstName': 'Alex'}, {'age': 7, 'firstName': 'Bob'}],
 'firstName': 'Jane',
 'hobbies': ['running', 'swimming', 'singing'],
 'lastName': 'Doe'}

lets say we have python dictionary and convert it into json format this is also called SERIALIZATION or ENCODING

In [ ]:
import json

person = {"name": "John", "age": 30, "city": "New York", "hasChildren": False, "titles": ["engineer", "programmer"]}

# convert into JSON:
person_json = json.dumps(person)
print(person_json)

{"name": "John", "age": 30, "city": "New York", "hasChildren": false, "titles": ["engineer", "programmer"]}


In [ ]:
person_json2 = json.dumps(person, indent=4, separators=("; ", "= "), sort_keys=True)
# the result is a JSON string: 
print(person_json2) 

{
    "age"= 30; 
    "city"= "New York"; 
    "hasChildren"= false; 
    "name"= "John"; 
    "titles"= [
        "engineer"; 
        "programmer"
    ]
}


lets say we have json data and we want to convert it back to python data this is called deserilization or decoding

In [ ]:
import json

person = {"name": "John", "age": 30, "city": "New York", "hasChildren": False, "titles": ["engineer", "programmer"]}

# convert into JSON:
person_json = json.dumps(person)

person = json.loads(person_json)
print(person)

{'name': 'John', 'age': 30, 'city': 'New York', 'hasChildren': False, 'titles': ['engineer', 'programmer']}


#rabdom numbers

Python defines a set of functions that are used to generate or manipulate random numbers. This article covers:

the random module
reproduce numbers with random.seed()

create cryptographically strong random numbers with the secrets module

create random nd arrays with numpy.random

In [ ]:
import random

# random float in [0,1)
a = random.random()
print(a)

# random float in range [a,b]
a = random.uniform(1,10)
print(a)

# random integer in range [a,b]. b is included
a = random.randint(1,10)
print(a)

# random integer in range [a,b). b is excluded
a = random.randrange(1,10)
print(a)

# random float from a normal distribution with mu and sigma
a = random.normalvariate(0, 1)
print(a)

# choose a random element from a sequence
a = random.choice(list("ABCDEFGHI"))
print(a)

# choose k unique random elements from a sequence
a = random.sample(list("ABCDEFGHI"), 3)
print(a)

# choose k elements with replacement, and return k sized list
a = random.choices(list("ABCDEFGHI"),k=3)
print(a)

# shuffle list in place
a = list("ABCDEFGHI")
random.shuffle(a)
print(a)

0.18505096341476068
3.757388105938565
10
9
0.19576109372036332
G
['D', 'I', 'E']
['B', 'A', 'I']
['H', 'I', 'A', 'B', 'F', 'E', 'G', 'C', 'D']


#Random numbers with NumPy

In [ ]:
import numpy as np

np.random.seed(1)
# rand(d0,d1,…,dn)
# generate nd array with random floats, arrays has size (d0,d1,…,dn)
print(np.random.rand(3))
# reset the seed
np.random.seed(1)
print(np.random.rand(3))

# generate nd array with random integers in range [a,b) with size n
values = np.random.randint(0, 10, (5,3))
print(values)

# generate nd array with Gaussian values, array has size (d0,d1,…,dn)
# values from standard normal distribution with mean 0.0 and standard deviation 1.0
values = np.random.randn(5)
print(values)

# randomly shuffle a nd array.
# only shuffles the array along the first axis of a multi-dimensional array
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.random.shuffle(arr)
print(arr)

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[[5 0 0]
 [1 7 6]
 [9 2 4]
 [5 2 4]
 [2 4 7]]
[-2.29230928 -1.41555249  0.8858294   0.63190187  0.04026035]
[[4 5 6]
 [7 8 9]
 [1 2 3]]


#copy

In [1]:
org=[1,2,3,4,5]
cpy=org
cpy[0]=-10
print(cpy)
print(org)  #the original will also changed

[-10, 2, 3, 4, 5]
[-10, 2, 3, 4, 5]


In [3]:
#shallow copy
import copy
org=[1,2,3,4,5]
cpy=copy.copy(org)
cpy[0]=-10
print(cpy)
print(org)  

[-10, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [4]:
#shallow copy is only one level deep
org=[[0,1,2,3,4],[5,6,7,8,9]]
cpy=copy.copy(org)
cpy[0][1]=-10
print(cpy)
print(org)

[[0, -10, 2, 3, 4], [5, 6, 7, 8, 9]]
[[0, -10, 2, 3, 4], [5, 6, 7, 8, 9]]


In [5]:
org=[[0,1,2,3,4],[5,6,7,8,9]]
cpy=copy.deepcopy(org)  #original doent get affected
cpy[0][1]=-10
print(cpy)
print(org)

[[0, -10, 2, 3, 4], [5, 6, 7, 8, 9]]
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
